### ISSUE TITLE
Annotations not recording when touching right and left borders

### ISSUE THREAD

**Issue by JessCappadonna** [QutBioacoustics/baw-client#276] opened 2016-07-19 05:55 UTC
When creating "airplane" annotations, they often touch right, left and bottom boarders of the spectogram on the listen page. When clicking the back button I discovered a previously made annotation had not save of touching the right and left border. The bottom border seems to have no affect. I am not sure how many annotations did not record since I have been using the site as it is unusual behaviour for me to go back 30 seconds and review a recently made annotation. 

Screenshot of an annotation this would happen with once changing screens: https://gyazo.com/4c4648a665605f8c8762d44178de662a

**Comment by atruskie** [comment] 2016-07-19 06:05
Closing as duplicate of #268 

The good news is your annotation is being saved! If you read through the description of #268 you should realize that the annotation is being saved but because it is slightly too long, and when the page reloads it is filtered out.

Note it has nothing to do with the _airplane_ tag.

Bad news is that #268 will be hard to fix.

**Closed by atruskie** 2016-07-19 06:05 UTC
Labels: bug, duplicate
