### ISSUE TITLE
Logged out when going from baw-server page to baw-client page

### ISSUE THREAD

**Issue by cofiem** [QutBioacoustics/baw-client#258] opened 2016-02-20 09:53 UTC
Repro steps:

1. clear cache and cookies and active logins (ff)
2. go to https://ecosounds.org/
3. click on 'Log In' in top right
4. enter username & password (now logged in, on https://www.ecosounds.org/ )
5. click on 'Listen' link on top nav
6. Problem occurs:
    - (expected) show list of recent recordings, still logged in
    - (actual) redirected to ['Unauthorized' page](https://www.ecosounds.org/errors/unauthorized?redirect_to=https:%2F%2Fecosounds.org%2Flisten)

If you visit any baw-client page before logging in (even if you get redirected to 'Unauthorized' page), going to a baw-client page will work after logging in.

**Comment by atruskie** [comment] 2016-02-20 10:03
Cannot reproduce, FF version 43.0.1. No other tabs open. Non admin user. Cache cleared completely.

**Comment by cofiem** [comment] 2016-02-20 10:28
Turns out this was related to apex vs www domains.

**Comment by atruskie** [comment] 2016-02-20 10:28
Repro'd by going to APEX domain. This is an issue with hosting - cookies don't apply to multiple sub domains and baw-client's resources are hard wired for www. Closing as actual issue tracked here: https://github.com/QutBioacoustics/baw-private/issues/113

**Closed by atruskie** 2016-02-20 10:28 UTC
Labels: bug, triage:medium

**Comment by atruskie** [comment] 2016-12-07 04:33
FYI all (including @JessCappadonna) this issue has finally been resolved. The website is now only served under the `www.` subdomain.
